name: Backend Check

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.4'

      - name: Install dependencies
        working-directory: ./app/backend
        run: go mod download

      - name: Install GolangCI-Lint
        working-directory: ./app/backend
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.62.2
          golangci-lint --version

      - name: Lint
        working-directory: ./app/backend
        run: golangci-lint run
